### ISSUE TITLE
数字ID错误

### ISSUE THREAD

**Issue by Dr-WeiAL** [Bkm016/TabooMenu#14]
所有数字ID都会变成基岩
包括mod的
如果是'171:1'这样的,连贴图都没有
求解
[图片.zip](https://github.com/Bkm016/TabooMenu/files/3391651/default.zip)

**Comment by Arasple** [comment]
已修复。重新下载 v2.63

**Comment by Dr-WeiAL** [comment]
> 已修复。重新下载v2.63

我就是用的2.63版本,游戏版本是1.12.2,原版和mod的数字id都不能用
