### ISSUE TITLE
PlaceholderAPI插件重载后%TabooMenu_js: %公式会失效

### ISSUE THREAD

**Issue by ivxiaohangvi** [Bkm016/TabooMenu#16]
PlaceholderAPI插件使用/papi reload指令重载后
%TabooMenu_js: %公式会失效[没有报错]
![图片](https://user-images.githubusercontent.com/41426821/61991695-d2c8ec00-b086-11e9-8359-e7091c00fef7.png)
服务器重启后恢复正常
PlaceholderAPI2.9.2 和2.10.3均有这个问题
TabooMenuv2.63以前版本也有

**Comment by Arasple** [comment]
已修复。请重新下载 v2.63
